[project]
name = "mcp-practise"
version = "0.1.0"
description = "A simple project to learn about Model Context Protocol"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.51.0",
    "mcp[cli]>=1.27.2",
    "prompt-toolkit>=3.0.51",
    "python-dotenv>=1.1.0",
]
[tool.uv]
index-url = "https://pypi.org/simple/"